[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"         # Set the Solidity Compiler version
evm_version = "cancun"  # Set the EVM version
optimize = true         # Enable Solidity optimizer
optimizer_runs = 200    # Set the number of optimizer runs
via_ir = true           # Enable IR generation (Used for custom errors in require statements)

# Set any warnings to ignore for specific files (e.g. selfDestruct when used in tests to force send ETH)
ignored_warnings_from = ["src/Level7.sol"] # Ignore warnings from selfDestruct in Level7.sol

# Set the remappings for the Solidity compiler
remappings = [
    "@foundry-devops/=lib/foundry-devops/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solmate=lib/solmate/src/"
    ]

# Allow foundry to run commands on the command line
ffi = true 
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config